server{
    listen <8080>
    listen [::]<8080>;
    server_name<DESKTOP-BAIK6RQ>;
    root <WEB_ROOT>;
    index <index.html>;
    access_log /var/log/nginx/lathephong.access_log;
    error_log /var/log/nginx/lathephong.error_log
    location/{
        <ALLOW_DIRECTIVE>;
        try_files $uri/=404;
    }

}